# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20170417_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='head_img',
            field=models.ImageField(upload_to='upload/article', verbose_name='文章标题图片'),
        ),
    ]
